//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    
    public partial class Ogrenciler
    {
        public Ogrenciler()
        {
            this.Odunc = new HashSet<Odunc>();
        }
    
        public int id { get; set; }
        public string ogrenciNo { get; set; }
        public string ogrenciAd { get; set; }
        public string ogrenciSoyad { get; set; }
        public int bolumID { get; set; }
        public string adres { get; set; }
        public string memleketAdres { get; set; }
        public System.DateTime kayitTarih { get; set; }
        public string cepTelefon { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual ICollection<Odunc> Odunc { get; set; }


        public static Ogrenciler GetOgrenciler( string ogrenciNo )
        {
            KutuphaneDBEntities DB = new KutuphaneDBEntities();

            return GetOgrenciler( ogrenciNo, DB );
        }

        public static Ogrenciler GetOgrenciler(string ogrenciNo, KutuphaneDBEntities DB )
        {
            return DB.Ogrenciler.Single( e => e.ogrenciNo == ogrenciNo );
        }
    }
}
